version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80 # 将主机的 8000 端口映射到容器的 80 端口
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-web3-voting:/var/www/html/wp-content/plugins/wp-web3-voting
      - wordpress_data:/var/www/html # 持久化 WordPress 数据
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7 # 使用 MySQL 5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql_data:/var/lib/mysql # 持久化 MySQL 数据
    restart: always

volumes:
  wordpress_data:
  mysql_data:
